'use strict';

module.exports = {
  APP_TO_CONTENT_SCRIPT: {
  	GET_IMG_DATA_URI: 'GET_IMG_DATA_URI',
  	GET_IMGS: 'GET_IMGS',
  	ZIP_IMGS: 'ZIP_IMGS',
  	RECEIVE_IMAGE_BLOB: 'RECEIVE_IMAGE_BLOB'
  },
  CONTENT_SCRIPT_TO_APP: {
  	GENERATE_BLOB_AS_ZIP:'GENERATE_BLOB_AS_ZIP',
  	GENERATE_BLOB_AS_ZIP_PROGRESSION: 'GENERATE_BLOB_AS_ZIP_PROGRESSION',
  	RECEIVE_ZIP_BLOB: 'RECEIVE_ZIP_BLOB'
  }
};
